# run

run_dev_stack_up:
  extends:
    - .stack_command
    - .stack_services
    - .development_variables
    - .rules_development_manual
  stage: run_up
  variables:
    DOCKER_COMMAND1: "docker-compose down"
    DOCKER_COMMAND2: "docker-compose up -d"
    EXECUTION_PATH: $PROJECT_ROOT_PATH/current


run_dev_elasticStack_up:
  extends: 
    - .run_service_template
    - .development_variables
    - .rules_development_manual
  stage: run_up
  variables:
    SERVICE_DIRECTORY: zammad-docker
    COMMAND: "up -d"

run_dev_elasticStack_down:
  extends: 
    - .run_service_template
    - .development_variables
    - .rules_development_manual
  stage: run_down
  variables:
    SERVICE_DIRECTORY: zammad-docker
    COMMAND: down

run_staging_stack_up:
  extends:
    - .stack_command
    - .stack_services
    - .staging_variables
    - .rules_staging_manual
  stage: run_up
  variables:
    DOCKER_COMMAND1: "docker-compose down"
    DOCKER_COMMAND2: "docker-compose up -d"
    EXECUTION_PATH: $PROJECT_ROOT_PATH/current
    
run_staging_elasticStack_up:
  extends: 
    - .run_service_template
    - .staging_variables
    - .rules_staging_manual
  stage: run_up
  variables:
    SERVICE_DIRECTORY: zammad-docker
    COMMAND: "up -d"

run_staging_elasticStack_down:
  extends: 
    - .run_service_template
    - .staging_variables
    - .rules_staging_manual
  stage: run_down
  variables:
    SERVICE_DIRECTORY: zammad-docker
    COMMAND: down
