# templates for build

.build_step1:
  stage: build_1
  script:
   - NETWORK_NAME=infrastructure_default
   - if [ -z $(docker network ls --filter name=^${NETWORK_NAME}$ --format="{{ .Name }}") ] ; then 
      docker network create ${NETWORK_NAME} ; 
     fi
   - rsync -rltgoEDvz -e "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" * $PROJECT_ROOT_PATH/$CI_PIPELINE_ID
   - cd $PROJECT_ROOT_PATH/$CI_PIPELINE_ID
   - pwd

.build_step2:
  stage: build_2
  extends:
    - .stack_command
    - .stack_services
  variables:
    DOCKER_COMMAND1: "docker-compose build"
    DOCKER_COMMAND2: echo "no command"
    EXECUTION_PATH: $PROJECT_ROOT_PATH/$CI_PIPELINE_ID

